const APIURL = process.env.REACT_APP_API_URL;
const APPNAME = process.env.REACT_APP_APP_NAME;
const APPVERSION = process.env.REACT_APP_APP_VERSION;
const MSAL_CLIENT_ID = process.env.REACT_APP_MSAL_CLIENT_ID;
const MSAL_SCOPE = process.env.REACT_APP_MSAL_SCOPE;
const DEFAULT_SPLIT_CHAR  = process.env.REACT_APP_DEFAULT_SPLIT_CHAR;
const DATEFORMAT = process.env.REACT_APP_DATE_FORMAT;
const DATE_TIME_FORMAT = process.env.REACT_APP_DATE_TIME_FORMAT;
const FORMAL_DATE_FORMAT = process.env.REACT_APP_FORMAL_DATE_FORMAT
const FORMAL_DATE_TIME_FORMAT = process.env.REACT_APP_FORMAL_DATE_TIME_FORMAT;
const TIMEZONE_OFFSET = (new Date()).getTimezoneOffset();
const MS_GRAPH_API_URL = process.env.REACT_APP_MS_GRAPH_API_URL;

export {
    APIURL,
    APPNAME,
    APPVERSION,
    MSAL_CLIENT_ID,
    MSAL_SCOPE,
    DEFAULT_SPLIT_CHAR,
    DATEFORMAT,
    DATE_TIME_FORMAT,
    FORMAL_DATE_FORMAT,
    FORMAL_DATE_TIME_FORMAT,
    TIMEZONE_OFFSET,
    MS_GRAPH_API_URL
}